### ISSUE TITLE
Use key-value pairs in the Quick_Button message

### ISSUE THREAD

**Issue by britzl** [GamingBud/QuickButton#1]
The message to create a button looks like this according to the example:

	msg.post("#exampleGUI", "Quick_Button", {"ThisObject", "example", vmath.vector3(650,400,0), "system_font", "Hello World!"})

And it's handled like this:

	if message_id == hash("Quick_Button") then
		Create_Button(message[1],message[2],message[3],message[4],message[5])
	end

Wouldn't it be better to pass key-value pairs instead:

	msg.post("#exampleGUI", "Quick_Button", { owner = "ThisObject",  order = "example", pos = vmath.vector3(650,400,0), font = "system_font", text = "Hello World!"})

	if message_id == hash("Quick_Button") then
		Create_Button(message.owner, message.order, message.pos, message.font, message.text)
	end

**Comment by GamingBud** [comment]
It would be a lot better! I was always curious whether there was a smarter way to go about message table passing.

Modified in Version 0.2.
