### ISSUE TITLE
Global function declarations in QuickButton.gui_script

### ISSUE THREAD

**Issue by britzl** [GamingBud/QuickButton#2]
I would recommend that you try to avoid the creation of global functions. The Create_Button, Click_Button and Highlight_Button functions are all global. Add a `local` keyword in front of the function declarations and move then above the on_message and on_input functions from where they are used

**Comment by GamingBud** [comment]
Done, but what is the reason for securing them either in local or in a table? You can't call these function from another script unless it's a module, correct?

**Comment by britzl** [comment]
For gui_scripts it's not that bad to declare them as local outside of the lifecycle functions, but a local variable outside the lifecycle functions in a .script file would be shared by all script components of that type. Store the same variable on the self "table" would make the variable local to each script instance.

**Comment by GamingBud** [comment]
Gotcha. Thanks.
