### ISSUE TITLE
Comment about deleting buttons

### ISSUE THREAD

**Issue by britzl** [GamingBud/QuickButton#4]
In the docs you mention "If you wanted to delete the button on press, included in the message is the button number. You simply have to delete the nodes associated with that number and set that table entry to nil."

The thing though is that you cannot delete a gui node outside of the script in which it is created. This means that I cannot call `gui.delete()` from a script component or another gui_script component. It has to be from QuickButton.gui_script

**Comment by GamingBud** [comment]
You are absolutely right. I overlooked this fact.

Fixed in Version 0.2.
