### ISSUE TITLE
Try to avoid table and object creation

### ISSUE THREAD

**Issue by britzl** [GamingBud/QuickButton#6]
For performance reason you want to avoid table and object creation as much as possible. In your on_input function you create a new table every frame (which will generate garbage which will cause a gc hitch):

	Highlight_Button({x=action.x,y=action.y})

Wouldn't it be better to either pass the action table or the x and y values directly.	

	Highlight_Button(action.x, action.y)
or

	Highlight_Button(action)

The same goes for `Click_Button` where you create a vector3 which you really don't need since you only care about x and y for node picking

**Comment by GamingBud** [comment]
I'm not quite sure why I did it that way, although I do remember my thinking for Click_Button's vector3. I thought I needed the z value to use gui.pick_node, and then I didn't modify it once I found out.

Modified in Version 0.2.
